# -- 코드를 입력하세요
# SELECT CART_ID, COUNT(*)
# FROM CART_PRODUCTS , (SELECT CART_ID , DISTINCT NAME FROM CART_PRODUCTS ) AS P
# WHERE P.NAME = 'Milk' OR P.NAME = 'Yogurt' 
# GROUP BY CART_ID
# HAVING COUNT(DISTINCT NAME) > 3
SELECT CART_ID 
FROM CART_PRODUCTS 
WHERE NAME = 'Milk' or NAME = 'Yogurt'
GROUP BY CART_ID
HAVING COUNT(DISTINCT NAME) >= 2


